### ISSUE TITLE
Selecting text makes all notes turn white and requires a forced refresh (Windows/Mac only)

### ISSUE THREAD

**Issue by vyfpsujxwyzhgtxzonodieumaiysrb** [arturolinares/sn-rme#16] opened 2020-11-01 18:09 UTC
Selecting text makes all notes turn white and requires a forced refresh to fix.This issue persists on the standard and beta version of standard notes. 
This issue ONLY occurs on the Windows and Mac version of the application. The IOS and Web version of the application work fine.

This also happens extremely frequently on my machines. Please let me know if there's anything I can do to stop it.

**Here's the console error:** 
<img width="1124" alt="Screen Shot 2020-10-24 at 1 22 57 PM" src="https://user-images.githubusercontent.com/9138131/97810613-28eded00-1c43-11eb-9607-122c0e4c34c8.png">

<img width="812" alt="Screen Shot 2020-10-24 at 3 17 59 PM" src="https://user-images.githubusercontent.com/9138131/97810617-32775500-1c43-11eb-962f-06d9b54f8684.png">

**The steps that result in the error:**
1. Text selection made 
<img width="724" alt="1   (red is the selection made)" src="https://user-images.githubusercontent.com/9138131/97810580-d44a7200-1c42-11eb-86f2-9cbc835dbba3.png">

2. result after selection is made
<img width="709" alt="2  Selection made (It does not even give me the chance to copy the selection)" src="https://user-images.githubusercontent.com/9138131/97810581-d4e30880-1c42-11eb-9383-4ee505cde2aa.png">

3. result after forced refresh
<img width="709" alt="3  After command R" src="https://user-images.githubusercontent.com/9138131/97810582-d4e30880-1c42-11eb-90d8-9f07ec084275.png">

**Comment by environmentalcode** [comment] 2020-11-03 08:48
It happens also on my Linux distro (ArchLinux, Standard Notes 3.5.1.AppImage).

**Comment by fbartels** [comment] 2020-11-06 15:37
> result after forced refresh

what does "forced refresh" mean in this context? Force reload of a tab in Chrome?

**Comment by TechNickViews** [comment] 2020-11-06 15:51
It works fine in Chrome, the issue only occurs on the mac or windows desktop application.

And by forced refresh, I mean I am doing the (Command + r) or (ctrl + r) command while the standard notes app is open.

**Comment by fbartels** [comment] 2020-11-06 23:41
Ok, thanks. I've seen something similar, where the editor fails to load and does not show the note content and wanted to see if we are talking about the same reload.

I'm still collecting information and will open a ticket soon.

**Comment by arturolinares** [comment] 2020-11-23 15:58
Can't reproduce on Linux or Windows (v3.5.6). I wonder if this has to do with electron hardware acceleration. Is there any way to disable it to rule it out?

**Comment by arturolinares** [comment] 2021-02-21 17:26
Closing this because it looks it is not related to the editor.

**Closed by arturolinares** 2021-02-21 17:26 UTC
