### ISSUE TITLE
When repeatedly changing text selection using keyboard or mouse, the entire text content for all notes disappears

### ISSUE THREAD

**Issue by hirusi** [arturolinares/sn-rme#13] opened 2020-09-11 18:32 UTC
Bug reproducible on Standard Notes v3.4.2 and v3.4.4 desktop editor on Linux platform.

To reproduce:

- Open a note with text content in it
- Ensure Rich Markdown Editor is active
- Select any piece of text:
  - using the keyboard shortcut `Ctrl+Shift+Left` or `Ctrl+Shift+Right`, or,
  - using the mouse, start selecting the text and drag it around a few times to change text selection
- Text content disappears
- To resolve, restart Standard Notes

Here's a GIF showing both with mouse, then followed with an app restart, then the keyboard shortcut: https://imgur.com/a/O9aq5Aj

**Comment by joshl129** [comment] 2020-09-14 04:41
+1, was just about to post this. This is my favorite Standard Notes editor, but this issue is making it a bit unusable. I don't have much to add that OP didn't already cover, but let me know if I can help troubleshoot in any way, and thank you for all your work on this.

**Comment by hirusi** [comment] 2020-09-14 04:44
Are you on Linux as well?

I found out changing the editor and then back to RME also works to resolve the issue. Although I agree it is unusable for any long-form/serious writing at the moment.

**Comment by joshl129** [comment] 2020-09-14 04:52
I'm on Windows 10 actually. And ah good to know, thank you!

**Comment by phuna** [comment] 2020-09-22 02:24
I'm on Mac and having the same issue.
@hirusi 's workaround seems to work well for me.

**Comment by arturolinares** [comment] 2020-09-22 03:32
This is very strange. I can’t see that behavior on Windows or Linux. Does that happen also on the web version? I wonder if it is an electron bug.

**Comment by phuna** [comment] 2020-09-22 06:57
> This is very strange. I can’t see that behavior on Windows or Linux. Does that happen also on the web version? I wonder if it is an electron bug.
No it doesn't happen on web version (I tried on Firefox nightly).
Also on desktop version repeatedly selecting some text could trigger the issue as well (even after changing editor as @hirusi suggested)

**Comment by joshl129** [comment] 2020-09-24 00:48
Ah thank you! Like phuna said, I didn't experience this on Firefox. (I didn't think to try that because I thought the web version was less fully featured in some ways, but besides the unique context menu from right-click I don't see much difference.)

FWIW I also tried it in the [latest beta version of Rambox Pro](https://github.com/ramboxapp/download/releases/tag/v1.4.0-beta.1), which uses Electron 9.3.0. I didn't experience the issue there like I did on the desktop version of Standard Notes (I didn't realize SN ran on Electron).

Hope that this can get fixed at some point (let me know if I can help any further), but for now this is more than good enough for me to keep using this editor. Thanks again for all your work!

**Comment by phuna** [comment] 2020-10-18 12:55
FWIW I updated to the latest version 3.4.10 today and the issue is solved.

**Comment by hirusi** [comment] 2020-10-21 14:42
The web version does not appear to present this issue. Looks like it could be limited to Electron.

**Comment by phuna** [comment] 2020-10-22 15:44
> Are you certain? I just tried to use it again on SN 3.4.10. Although the issue took a longer time to surface at first, it eventually did show up again. Reinstalling the extension did not help.

@hirusi  It's working well for me so far, maybe I haven't used it long enough, but anyway it's still much better now

**Comment by arturolinares** [comment] 2021-07-29 14:40
Closing this issue, it seems it was resolved in a recent SN update.

**Closed** 2021-07-29 14:40 UTC
